# Change these first
owner: xqtc161 # Your GitHub organization or username, where this repository lives
repo: status-heroin-trade # The name of this repository

sites:
  - name: heroin.trade 
    url: https://heroin.trade
  - name: Jellyfin 
    url: https://jellyfin.heroin.trade
  - name: Forgejo 
    url: https://git.heroin.trade 
  - name: Nextcloud
    url: https://cloud.heroin.trade
  - name: Grafana
    url: https://grafana.heroin.trade
  - name: Lanraragi
    url: https://calibre.heroin.trade
  - name: Demo Fileserver
    url: https://demos.heroin.trade
  - name: marie.software
    url: https://marie.software
  - name: juvi.likes.graphics 
    url: https://juvi.likes.graphics

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.heroin.trade 
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/xqtc161/status-heroin-trade/refs/heads/master/assets/uwu.jpg 
  name: status.heroin.trade 
  introTitle: "Service Status Page" 
  introMessage: All these services run on the same host. Kinda unstable. I should not be trusted with computers. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: About
      href: https://heroin.trade

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
